name: Kotlin Lint Check

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.48.2/ktlint
          chmod a+x ktlint

      - name: Run ktlint check
        run: ./ktlint --color --log-level=debug --relative backend
