name: Pull Request spotlessCheck

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'graalvm' 
        java-version: '21'
        
    - name: Grant execute permissions to gradlew
      run: chmod +x ./backend/gradlew
      
    - name: Run spotlessApply
      working-directory: ./backend
      run: ./gradlew spotlessApply
      
    - name: Commit and push changes
      run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: apply Spotless formatting"
            git push origin HEAD:${{ github.head_ref }}
          fi
  
